language: go
go: 1.5
services:
  #- memcache # 
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/pa001024/reflex
  - go get -v github.com/pa001024/reflex/source
  - go get -v github.com/pa001024/reflex/filter
  - go get -v github.com/pa001024/reflex/target
  - go get -v github.com/pa001024/reflex/util
  - go get -v github.com/pa001024/reflex/util/ascgen
script:
  - go test github.com/pa001024/reflex/source
  - go test github.com/pa001024/reflex/filter
  - go test github.com/pa001024/reflex/target
  - go test github.com/pa001024/reflex/util
  - go test github.com/pa001024/reflex/util/ascgen
